package fort

import "k8s.io/client-go/tools/cache"

type TPod struct {
	NodeName string
	Label    string
}

type TService struct {
	Name     string
	SomeData string
}

type TServiceNode struct {
	Node    string
	Service string
	Count   int64
}

func (s *TService) Matches(pod *TPod) bool {
	return pod.Label[0] == s.SomeData[0]
}

type TNode struct {
	Name    string
	Domains []string
}

type TNodeDomain struct {
	Name   string
	Domain string
}

type TServiceDomain struct {
	Service string
	Domain  string
	Count   int64
}

type DomainCount struct {
	Domain string
	Count  int64
}

type TServiceInfo struct {
	Service      string
	DomainCounts []DomainCount
}

type PodSpreadLiteInfo struct {
	ServiceNodes   CloneableSharedInformerQuery
	NodeDomains    CloneableSharedInformerQuery
	ServiceDomains CloneableSharedInformerQuery
	ServiceInfo    CloneableSharedInformerQuery

	PodUpdates     ManualSharedInformer
	ServiceUpdates ManualSharedInformer
	NodeUpdates    ManualSharedInformer
}

func NewPodSpreadLiteInfo(podInformer, serviceInformer, nodeInformer cache.SharedInformer) *PodSpreadLiteInfo {
	d := &PodSpreadLiteInfo{}

	// Compute the number of pods on each node that match each service.
	d.ServiceNodes = QueryInformer(&GroupByJoin[*TServiceNode, *TPod, *TService]{
		Select: func(fields []GroupField) (*TServiceNode, error) {
			// Use the fields generated by GroupBy to create a new object
			// for each service / node group.
			return &TServiceNode{
				Service: fields[1].(string),
				Node:    fields[2].(string),
				Count:   fields[3].(int64),
			}, nil
		},

		// Full join the pod and service informers.
		From: podInformer,
		Join: serviceInformer,

		// We only care about entries where the pod matches the service.
		Where: func(pod *TPod, service *TService) bool {
			return service.Matches(pod)
		},

		// Group by service and node, and count the number of pods
		// for eaach service / node pair.
		GroupBy: func(pod *TPod, service *TService) (any, []GroupField) {
			return [2]string{service.Name, pod.NodeName},
				[]GroupField{
					AnyValue(service.Name),
					AnyValue(pod.NodeName),
					Count(),
				}
		},
	})

	// Create one entry for each node / domain pair.
	d.NodeDomains = QueryInformer(&FlatMap[*TNodeDomain, *TNode]{
		// For each node, create one entry for each domain
		// the node belongs to.
		Map: func(node *TNode) ([]*TNodeDomain, error) {
			ret := []*TNodeDomain{}
			for _, d := range node.Domains {
				ret = append(ret, &TNodeDomain{Name: node.Name, Domain: d})
			}
			return ret, nil
		},
		Over: nodeInformer,
	})

	// Join the service/node pod counts with the node/domain pairs.
	// Group by domain to get the total number of pods each service has in each domain.
	d.ServiceDomains = QueryInformer(&GroupByJoin[*TServiceDomain, *TServiceNode, *TNodeDomain]{
		Select: func(fields []GroupField) (*TServiceDomain, error) {
			return &TServiceDomain{
				Service: fields[1].(string),
				Domain:  fields[2].(string),
				Count:   fields[3].(int64),
			}, nil
		},
		From: d.ServiceNodes,
		Join: d.NodeDomains,
		On: func(service *TServiceNode, node *TNodeDomain) any {
			if service != nil {
				return [1]string{service.Node}
			} else {
				return [1]string{node.Name}
			}
		},
		Where: func(service *TServiceNode, node *TNodeDomain) bool {
			return service.Node == node.Name
		},
		GroupBy: func(service *TServiceNode, node *TNodeDomain) (any, []GroupField) {
			return [2]string{service.Service, node.Domain},
				[]GroupField{
					AnyValue(service.Service),
					AnyValue(node.Domain),
					Sum(service.Count),
				}
		},
	})

	// Flatten the results into one entry per service, with a sub array of domains and their counts.
	d.ServiceInfo = QueryInformer(&GroupBy[*TServiceInfo, *TServiceDomain]{
		Select: func(fields []GroupField) (*TServiceInfo, error) {
			return &TServiceInfo{
				Service:      fields[1].(string),
				DomainCounts: fields[2].([]DomainCount),
			}, nil
		},
		From: d.ServiceDomains,
		GroupBy: func(serviceDomain *TServiceDomain) (any, []GroupField) {
			return [1]string{serviceDomain.Service},
				[]GroupField{
					AnyValue(serviceDomain.Service),
					Distinct(DomainCount{Domain: serviceDomain.Domain, Count: serviceDomain.Count}),
				}
		},
	})

	return d
}

func (d *PodSpreadLiteInfo) Clone() *PodSpreadLiteInfo {
	nd := &PodSpreadLiteInfo{}

	nd.PodUpdates = NewManualSharedInformer()
	nd.ServiceUpdates = NewManualSharedInformer()
	nd.NodeUpdates = NewManualSharedInformer()

	locks := LockInformerSet([]CloneableSharedInformerQuery{d.ServiceNodes, d.NodeDomains, d.ServiceDomains, d.ServiceInfo})
	defer locks.Unlock()

	nd.ServiceNodes = d.ServiceNodes.Clone([]cache.SharedInformer{nd.PodUpdates, nd.ServiceUpdates})
	nd.NodeDomains = d.NodeDomains.Clone([]cache.SharedInformer{nd.NodeUpdates})
	nd.ServiceDomains = d.ServiceDomains.Clone([]cache.SharedInformer{nd.ServiceNodes, nd.NodeDomains})
	nd.ServiceInfo = d.ServiceInfo.Clone([]cache.SharedInformer{nd.ServiceDomains})

	return nd
}
