/*
Fort is almost a database (it's a datafort!). It is an in-memory engine for map-reduce and
join operations. All data in Fort is represented as memory key-value maps.
All the results of map-reduce and join are automatically updated as source data is updated.
All of the maps are fast cloneable so the entire "db" can be cloned quickly.
This makes it simple to generate complex data structures that are automatically
updated as data changes, and are easily fast cloneable.
*/
package fort

// A spec defines a set of views and maps that are constructed by Fort.
// A spec is then used to create a DataFort object.

type Spec interface {
	// Create a new entity in Fort. Each entity must have a unique name.
	//
	// There are three types of entities in Fort:
	//
	// InputView: An input view is a logical key value map that mirrors an
	// external data source. InputView's are kept up to date by external
	// code. All data in Fort is eventually derived from one or more input views.
	//
	// DerivedView: A derived view is a logical key value map that is computed
	// from one or more source views (either InputViews or DerivedViews). Fort
	// keeps derived views in sync with input views. There are a variety of
	// types of derived views in Fort (map-reduce, join, etc).
	//
	// Output: An output represents an external key value map.
	// For convenience in aggregating multiple derived views into a single
	// output, we represent external views as two layer maps with an
	// "attributeName" key for the second layer.
	//
	// Store: A store object mirrors the data from a view to an output.
	New(entity EntitySpec) error
}

// Create a new input view.
// This view starts empty, but the user can add and remove entries
// by getting a handle to it as an ExternalView object and calling
// update methods. All state in Fort is eventually derived from
// some input view.
func NewInputView[KeyType comparable](name string) EntitySpec {
	return newInputView[KeyType](name)
}

// Define a new derived view generated by running map reduce on the given source view.
//
// Logically map reduce will:
//   - call the mapper function on each key value pair in the original source. The mapper
//     function returns one or more key value pairs generated from the source key value pair.
//   - aggregate the results of all the mapper calls by key.
//   - call the reducer function on the set of values with a given key.
//   - save the reducer output in the result view with the given key.
func MapReduce[InputKeyType, OutputKeyType comparable](name string, mapper Mapper[InputKeyType, OutputKeyType], reducer Reducer, source string) EntitySpec {
	return newMapReduceFactory(name, mapper, reducer, source)
}

// Define a new derived view created by joining two source views.
// Logically FullJoin will create a new view with one entry for each pair of entries in the sources.
// The keys of the resulting view will be a JoinKey, the values will be a JoinValue.
func FullJoin[LeftKeyType, RightKeyType comparable](name, left, right string) EntitySpec {
	return fullJoinFactory[LeftKeyType, RightKeyType](name, left, right)
}

// Define a new derived view created by merging the given source maps.
// Logically, MergeJoin will create a new view with one entry for each entry in each source.
// The keys of the results map will be KeyType,. The input sources are a map from
// source name to source alias, which is used as the SourceName in the UnionKeys from that
// source.
func MergeJoin[KeyType comparable](name string, sources map[string]string) EntitySpec {
	return mergeJoinFactory[KeyType](name, sources)
}

// Create a new derived view that is the union of the given sources. The resulting view has
// keys that are NestedKey structs, where the InnerKey is set to the name of the source view
// and the key is set to the key from the view.
func Union[KeyType comparable](name string, sources map[string]string) EntitySpec {
	return newUnion[KeyType](name, sources)
}

func Materialize[KeyType comparable](name string, source string) EntitySpec {
	return newMaterializer[KeyType](name, source)
}

// Wrap a user provided output. Stores the results from
// the given source view to the given output.
func Listen(name string, listener KeyValueTarget, source string) EntitySpec {
	return listenerFactory(name, listener, source)
}

// Create a new empty spec.
func NewSpec() Spec {
	return newSpec()
}

// A datafort materializes all of the views and maps defined in a spec.
// External views' contents are managed directly by the user, but all other
// views and maps are automatically updated by Fort.
type DataFort interface {
	// Get returns the view or map associated with the given name.
	// The return value will either be an ExternalView, a KeyValueMap, or
	// an internal view which is not manipulatable externally.
	Get(mapName string) (any, bool)

	// Clone the current version of the DataFort.
	// The result is a copy of the DataFort that can be independently
	// updated.
	Clone() DataFort

	// Release a reference to a data fort.
	Release()
}

// Create a new DataFort from a spec.
// Note that once a spec is used to create a DataFort, it should
// no longer be modified.
func New(spec Spec) DataFort {
	return newDataFort(spec)
}

// Interfaces for keys and maps.

type KeyValue[KeyType comparable] struct {
	// Note that we use generics for keys because the number
	// of lookup and manipulation operations we do on keys
	// makes using interfaces expensive. Values are generally
	// just passed around, so using an interface works fine.
	Key KeyType

	// Note that values in Fort must be immutable. Once a value
	// is passed in using Update or from the result of a mapper,
	// it cannot be changed.
	Value any
}

// A view to mirror state from an external source.
type InputView[KeyType comparable] interface {
	// Add or update a given key value.
	// Note that the value passed in must be immutable;
	// once passed in it is owned by Fort and cannot be changed.
	Update(key KeyType, value any)

	// Delete the given key from the map.
	Delete(key KeyType)
}

// A map of key value pairs.
type KeyValueMap[KeyType comparable] interface {
	// Get the value associated with the given key.
	// The boolean is true if a value was found, false otherwise.
	Get(key KeyType) (any, bool)

	// Get an iterator over all of the key values
	// in the given map. This can be used in
	// "range" operations.
	All() KeyValueIterator[KeyType]
}

// An iterator returned from maps. Note that these iterators can be used
// in range operations.
type KeyValueIterator[KeyType comparable] func(yield func(key KeyType, value any) bool)

// Convenience wrapper for a list of key value pairs.
type KeyValueSet[KeyType comparable] []KeyValue[KeyType]

// MapReduce types.

// Map from an input key value pair to a set of output key value pairs.
// Note that the values used in the output key value pairs must be immutable;
// once returned they are owned by Fort and cannot be changed.
type Mapper[InputKeyType, OutputKeyType comparable] func(kv *KeyValue[InputKeyType]) KeyValueSet[OutputKeyType]

// Common reducers.
// To define a custom reducer, see the interfaces in reducers.go.

var (
	// Store some value for each mapper key currently in the system. This assumes that the
	// value for a given key is either always the same or irrelevant, so getting any value
	// that has had this key at some point is acceptable.
	AnyValue = anyValueReducerFactory

	// Count the number of key value pairs that have the given key. Note this counts
	// the number of key value pairs with this key, not the number of distinct values
	// with this key. For distinct values use the "Set" reducer instead.
	Count = countReducerFactory

	// Assumes values are ints. Keeps a sum of all the values with a given key.
	Sum = sumReducerFactory

	// Construct a set of distinct mapper values that have the given mapper key.
	// The result for each mapper key is a sets.Set[any], where the values are all
	// of the values associated with the given mapper key.
	Set = setReducerFactory

	// Assumes the values in the mapper returns are themselves KeyValue[InnerKeyType]. For
	// each outer key (the key to the mapper key values) it will construct a map made up of the
	// inner KeyValue pairs (i.e. the values of the mapper key value returns). This assumes
	// that the inner keys are unique; i.e. it assumes no duplicate entries.
	// Map[InnerKeyType comparable]
)

// Types used in join.

// The key type used in the result from FullJoin.
type JoinKey[LeftKeyType, RightKeyType comparable] struct {
	Left  LeftKeyType
	Right RightKeyType
}

// The value type used in the results from Joins.
type JoinValue struct {
	Left  any
	Right any
}

type UnionKey[KeyType comparable] struct {
	// Name of the source view for this key value.
	SourceName string

	// The key from the source map.
	Key KeyType
}

// A target to store the results from a view.
type KeyValueTarget interface {
	OnUpdate(key any, value any, source KeyValueSource)
	OnDelete(key any, value any, source KeyValueSource)
}
