/*
Fort is almost a database (it's a datafort!). It is an in-memory engine for mapreduce and
join operations. All data in fort is represented as memory key-value maps.
All the results of mapreduces and joins are automatically updated as source data is updated.
All of the maps are fast cloneable so the entire "db" can be cloned quickly.
This makes it simple to generate complex data structures that are automatically
updated as data changes, and are easily fast cloneable.
*/
package fort

// A spec defines a set of views and maps that are constructed by fort.
// A spec is then used to create a DataFort object.

type Spec interface {
	// Create a new item, either a view or a map, from
	// a given source spec.
	//
	// Most items are "views" which are derived from some operator and can be then used as the
	// input to other operators but are not directly queryable.
	//
	// A view can be converted into a "map" using Materialize.
	// Maps can be queried directly by getting a handle to them as a KeyValueMap[KeyType].
	New(name string, source *SourceSpec) error
}

// Used with the spec "New" call. Create a view to reflect an external data source.
// This view starts empty, but the user can add and remove entries
// by getting a handle to it as an ExternalView object and calling
// update methods. All state in fort is eventually derived from
// some external view.
func NewExternalView[KeyType comparable]() *SourceSpec {
	return &SourceSpec{
		Create: func(s DataFort, name string, isClone bool) (any, error) {
			return makeOrCloneMap[KeyType](s.(*dataFort), name, isClone), nil
		},
		Dependencies: []string{},
	}
}

// Used with the spec "New" call. Define a new view generated by running map reduce on the given source view.
//
// Logically map reduce will:
//   - call the mapper function on each key value pair in the original source. The mapper
//     function returns one or more key value pairs generated from the source key value pair.
//   - aggregate the results of all the mapper calls by key.
//   - call the reducer function on the set of values with a given key.
//   - save the reducer output in the result view with the given key.
func MapReduce[InputKeyType, OutputKeyType comparable](mapper Mapper[InputKeyType, OutputKeyType], reducer Reducer, source string) *SourceSpec {
	return newMapReduceFactory(mapper, reducer, source)
}

// Used with the spec "New" call. Define a new view created by joining two source views.
// This will create a new view with one entry for each pair of entries in the sources.
// The keys of the resulting view will be a JoinKey, the values will be a JoinValue.
func FullJoin[LeftKeyType, RightKeyType comparable](left, right string) *SourceSpec {
	return fullJoinFactory[LeftKeyType, RightKeyType](left, right)
}

// Used with the spec "New" call. Convert a view into a map. Only maps created using materialize
// are directly queryable as KeyValueMaps.
func Materialize[KeyType comparable](source string) *SourceSpec {
	return newMaterializer[KeyType](source)
}

// Create a new empty spec.
func NewSpec() Spec {
	return newSpec()
}

// A datafort materializes all of the views and maps defined in a spec.
// External views' contents are managed directly by the user, but all other
// views and maps are automatically updated by Fort.
type DataFort interface {
	// Get returns the view or map associated with the given name.
	// The return value will either be an ExternalView, a KeyValueMap, or
	// an internal view which is not directly manipulatable externally.
	Get(mapName string) (any, bool)

	// Clone the current version of the DataFort.
	// The result is a copy of the DataFort that can be independently
	// updated.
	Clone() DataFort
}

// Create a new DataFort from a spec.
// Note that once a spec is used to create a DataFort, it should
// no longer be modified.
func New(spec Spec) DataFort {
	return newDataFort(spec)
}

// Interfaces for keys and maps.

type KeyValue[KeyType comparable] struct {
	// Note that we use generics for keys because the number
	// of lookup and manipulation operations we do on keys
	// makes using interfaces expensive. Values are generally
	// just passed around, so using an interface works fine.
	Key KeyType

	// Note that values in Fort must be immutable. Once a value
	// is passed in using Update or from the result of a mapper,
	// it cannot be changed.
	Value any
}

type KeyValueMap[KeyType comparable] interface {
	// Get the value associated with the given key.
	// The boolean is true if a value was found, false otherwise.
	Get(key KeyType) (any, bool)

	// Get an iterator over all of the key values
	// in the given map. This can be used in
	// "range" operations.
	All() KeyValueIterator[KeyType]
}

// A view to mirror state from an external source.
type ExternalView[KeyType comparable] interface {
	// Add or update a given key value.
	// Note that the value passed in must be immutable;
	// once passed in it is owned by Fort and cannot be changed.
	Update(key KeyType, value any)

	// Delete the given key from the map.
	Delete(key KeyType)
}

// An iterator returned from maps. Note that these iterators can be used
// in range operations.
type KeyValueIterator[KeyType comparable] func(yield func(key KeyType, value any) bool)

// Convenience wrapper for a list of key value pairs.
type KeyValueSet[KeyType comparable] []KeyValue[KeyType]

// MapReduce types.

// Map from an input key value pair to a set of output key value pairs.
// Note that the values used in the output key value pairs must be immutable;
// once returned they are owned by Fort and cannot be changed.
type Mapper[InputKeyType, OutputKeyType comparable] func(kv *KeyValue[InputKeyType]) KeyValueSet[OutputKeyType]

// Common reducers.
// To define a customer reducer, see the interfaces in reducers.go.

var (
	// Store some value for each mapper key currently in the system. This assumes that the
	// value for a given key is either always the same or irrelevant, so getting any value
	// that has had this key at some point is acceptable.
	AnyValue = anyValueReducerFactory

	// Count the number of key value pairs that have the given key. Note this counts
	// the number of key value pairs with this key, not the number of distinct values
	// with this key. For distinct values use the "Set" reducer instead.
	Count = countReducerFactory

	// Assumes values are ints. Keeps a sum of all the values with a given key.
	Sum = sumReducerFactory

	// Construct a set of distinct mapper values that have the given mapper key.
	// The result for each mapper key is a sets.Set[any], where the values are all
	// of the values associated with the given mapper key.
	Set = setReducerFactory
)

// Types used in join.

// The key type used in the result from FullJoin.
type JoinKey[LeftKeyType, RightKeyType comparable] struct {
	Left  LeftKeyType
	Right RightKeyType
}

// The value type used in the results from Joins.
type JoinValue struct {
	Left  any
	Right any
}
